ignored:
  - DL3018
    # DL3018 warning: Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
    # future: renovate investigation needed
  - DL3003
    # DL3003 warning: Use WORKDIR to switch to a directory
    # In GitHub Actions, the repository workspace is bind-mounted into the container at /github/workspace and steps run from that path by default.
    # Setting WORKDIR to a different location in these Dockerfiles can break relative paths that assume /github/workspace.
    # We intentionally omit WORKDIR here and ignore DL3003 for these Dockerfile(s).
