name: _linter
run-name: "_linter: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  reusable-linter:
    uses: ulfiac/commons/.github/workflows/reusable_linter.yaml@2c1c948ece43a579519cdcc30a66653c05bbe767 # v1.0.7
    with:
      terraform-fmt: false
      terragrunt-hcl-fmt: false
      tflint: false
