name: _linter
run-name: "_linter: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  reusable-linter:
    uses: ulfiac/commons/.github/workflows/reusable_linter.yaml@e88e32a21a8bfa5c701de365c44fe9c37a8d42a8 # v1.0.6
    with:
      terraform-fmt: false
      terragrunt-hcl-fmt: false
      tflint: false
