name: _purge

on:
  schedule:
    - cron: '53 10 * * *' # run daily at 10:53 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read
  packages: write

jobs:
  purge-runs:
    uses: ulfiac/commons/.github/workflows/reusable_purge_workflow_logs.yaml@e88e32a21a8bfa5c701de365c44fe9c37a8d42a8 # v1.0.6

  purge-packages:
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ github.token }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - terraform-fmt
          - terragrunt-hcl-fmt
          - tflint
          - utils
    steps:
      - name: Delete untagged versions
        run: |
          gh api "/users/${{ github.repository_owner }}/packages/container/${{ matrix.package }}/versions" --paginate \
            --jq '.[] | select(.metadata.container.tags | length == 0) | .id' \
          | while read -r id; do
              gh api -X DELETE "/users/${{ github.repository_owner }}/packages/container/${{ matrix.package }}/versions/${id}"
            done

      - name: Delete old tagged versions, keep newest 3
        run: |
          gh api "/users/${{ github.repository_owner }}/packages/container/${{ matrix.package }}/versions" \
            --jq '[.[] | select(.metadata.container.tags | length > 0)] | sort_by(.updated_at) | reverse | .[3:][] | .id' \
          | while read -r id; do
              gh api -X DELETE "/users/${{ github.repository_owner }}/packages/container/${{ matrix.package }}/versions/${id}"
            done
