name: _purge_workflow_runs

on:
  schedule:
    - cron: '53 8 * * *'  # daily, 08:53 UTC (03:53 EST, 04:53 EDT)
  workflow_dispatch:

permissions:
  actions: write
  contents: read
  packages: write

jobs:
  purge-workflow-runs:
    uses: ulfiac/commons/.github/workflows/reusable_purge_workflow_runs.yaml@21601aa5ad70c1a590a49ca46769ee155f908456 # v1.0.48
