name: _purge

on:
  schedule:
    - cron: '53 10 * * *' # run daily at 10:53 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  purge-logs:
    uses: ulfiac/commons/.github/workflows/reusable_purge_workflow_logs.yaml@5f7d2e10a21193bb50d8f3b4bd76c299f7b354bc # v1.0.5
