name: _purge_workflow_runs

on:
  schedule:
    - cron: '53 8 * * *'  # daily, 08:53 UTC (03:53 EST, 04:53 EDT)
  workflow_dispatch:

permissions:
  actions: write
  contents: read
  packages: write

jobs:
  purge-workflow-runs:
    uses: ulfiac/commons/.github/workflows/reusable_purge_workflow_runs.yaml@26597912dca955a3e03f1c086058a51ece294bbb # v1.0.22
