name: _purge_workflow_runs

on:
  schedule:
    - cron: '53 8 * * *'  # daily, 08:53 UTC (03:53 EST, 04:53 EDT)
  workflow_dispatch:

permissions:
  actions: write
  contents: read
  packages: write

jobs:
  purge-workflow-runs:
    uses: ulfiac/commons/.github/workflows/reusable_purge_workflow_runs.yaml@e6bcdf30df57979c9127c2b8b3b407365e34b700 # v1.0.38
