name: build terragrunt-hcl-fmt

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build_terragrunt_hcl_fmt.yaml
      - terragrunt-hcl-fmt/**

permissions:
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Read Terragrunt version
        id: version
        run: echo "value=$(cat terragrunt-hcl-fmt/.terragrunt-version)" >> "$GITHUB_OUTPUT"

      - uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: terragrunt-hcl-fmt
          platforms: linux/amd64
          push: true
          build-args: TERRAGRUNT_VERSION=${{ steps.version.outputs.value }}
          tags: |
            ghcr.io/ulfiac/terragrunt-hcl-fmt:${{ steps.version.outputs.value }}
